services:
  frontend:
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    # environment:
    #   - RACK_ENV=development
    #   - SHOW=true
    #   - SESSION_SECRET
    volumes:
      - "${PWD}/ddata:/data"